apiVersion: v1
kind: Service
metadata:
  annotations:
    cis.f5.com/ipamLabel: Test
  labels:
    app: coffee
  name: coffee-lb
  namespace: sample-app
spec:
  ports:
    - name: coffee-svc-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: coffee
  type: LoadBalancer
